### ISSUE TITLE
DEFINICIÓN DE REQUERIMIENTOS FUNCIONALES DEL APLICATIVO

### ISSUE THREAD

**Issue by Jahnnnn** [Jahnnnn/WIKI-CDA#2]
Se requiere establecer las funcionalidades de cada módulo.

**Comment by Jahnnnn** [comment]
Se establece una plantilla predeterminada:


[plantilla de requerimientos funcionales.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12374323/plantilla.de.requerimientos.funcionales.xlsx)

**Comment by Dafefrasu10** [comment]
Modulo de registro
[Requerimientos registro.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12413541/Requerimientos.registro.xlsx)

**Comment by PabloKxX** [comment]
Modulo de usuarios. 
[MU001 .xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434338/MU001.xlsx)
[MU002.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434339/MU002.xlsx)
[MU003.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434340/MU003.xlsx)
[MU004.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434341/MU004.xlsx)

**Comment by Jahnnnn** [comment]
Módulo de autenticación:


[MAU001.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434344/MAU001.xlsx)
[MAU002.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434345/MAU002.xlsx)

**Comment by Jahnnnn** [comment]
Módulo de configuración:


[MC001.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434348/MC001.xlsx)
[MC002.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12434349/MC002.xlsx)

**Comment by Dafefrasu10** [comment]
Módulo de pre-registro:

[_MPR003.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458896/_MPR003.xlsx)
[MPR001.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458899/MPR001.xlsx)
[MPR002.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458900/MPR002.xlsx)
[MPR004.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458901/MPR004.xlsx)

Módulo de registro:

[MR001.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458902/MR001.xlsx)
[MR002.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458903/MR002.xlsx)
[MR003.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458904/MR003.xlsx)
[MR004.xlsx](https://github.com/Jahnnnn/WIKI-CDA/files/12458905/MR004.xlsx)

**Comment by Jahnnnn** [comment]
Se da por finalizada la tarea.
