### ISSUE TITLE
DEFINICIÓN DE DIAGRAMAS UML

### ISSUE THREAD

**Issue by Jahnnnn** [Jahnnnn/WIKI-CDA#3]
![Image](https://github.com/Jahnnnn/WIKI-CDA/assets/87740551/a0ef3952-d4ee-4789-8ac5-620a262910ff)

Se requiere desarrollar por cada módulo los siguientes diagramas:

1. Diagramas de clases.
2. Diagramas de actividades.
3. Diagramas de casos de uso.

Cada modulo tiene definido sus respectivos requerimientos funcionales y se requiere que según cada requerimiento realizar los respectivos diagramas anteriores.

/estimate 1w

**Comment by Dafefrasu10** [comment]
![Captura de Pantalla 2023-09-04 a la(s) 1 53 51 p m](https://github.com/Jahnnnn/WIKI-CDA/assets/142549624/5de64052-0170-4c77-b025-e72d1681dda0)
![Captura de Pantalla 2023-09-04 a la(s) 1 54 18 p m](https://github.com/Jahnnnn/WIKI-CDA/assets/142549624/bbf65952-5306-4ed4-9dee-435b5daabd33)

**Comment by Jahnnnn** [comment]
Módulo de configuración:

![Image](https://github.com/Jahnnnn/WIKI-CDA/assets/87740551/303e6e66-e532-40f0-80be-1a895d41e995)

![Image](https://github.com/Jahnnnn/WIKI-CDA/assets/87740551/a5542228-fa8a-4aa8-9941-d8f39c66f359)



Módulo de autenticación:

![Image](https://github.com/Jahnnnn/WIKI-CDA/assets/87740551/f83a760c-2740-496f-9cba-eaf51cfe46f8)

![Image](https://github.com/Jahnnnn/WIKI-CDA/assets/87740551/5af1c86d-d8fd-411a-b059-00cf26fd8224)
